FROM elixir:1.15-alpine

RUN apk add --no-cache build-base npm git python3 inotify-tools

WORKDIR /app

# Install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

ENV MIX_ENV=dev

EXPOSE 4000

CMD ["mix", "phx.server"]